### ISSUE TITLE
🐛 Bug: About page doesn't load on Ubuntu

### ISSUE THREAD

**Issue by bywasik** [KL13NT/clippy#23]
**To Reproduce**
1. clone this repo
2. install dependencies
3. npm run dev
2. click `About` in the top-left corner
4. blank page

**Expected behavior**
page with content

**Screenshots**
![image](https://user-images.githubusercontent.com/57839948/107117604-b44ad000-687b-11eb-967a-c425a129b578.png)

**Environment (please complete the following information):**
 - OS: [Ubuntu 20.10]
 - Version [Clippy@1.2.0]

**Additional context**
It can be fixed by changing
```js 
aboutWindow.loadURL(path.join(__dirname, "about.html"))
```
to

```js 
aboutWindow.loadURL(`file://${__dirname}/about.html`)
```

**Comment by bywasik** [comment]
@KL13NT could you check it out?

**Comment by KL13NT** [comment]
I'll make sure to reproduce it when I have the time. I tested the same feature on Kali and there was no bugs, so will need to confirm it on Ubuntu before I can move on with it.

**Comment by KL13NT** [comment]
Have you tried the production build? Is it showing the same problems?

**Comment by KL13NT** [comment]
Confirmed production build on Ubuntu 18 LTS.

**Comment by KL13NT** [comment]
It seems that I'm using two different methods to load the HTML, which I shall change later. For now, the bug seems to stem from the fact that electron `Window.loadUrl` expect either a `file://` protocol url or a remote `http://` protocol one. `Window.loadFile` on the other hand expects a `path`, and resolves it. This is why it works for the `index.html` but not `about.html`, because the former uses `loadFile`, and the latter `loadUrl`. 

To fix it, use `loadUrl` consistently, and use [url.pathToFileURL](https://nodejs.org/api/url.html#url_url_fileurltopath_url) with `path.resolve` for both of them. This will make sure that the link is a correctly resolved path in file URL format.

Would look like `mainWindow.loadUrl(url.pathToFileURL(path.resolve(...)))`.

**Comment by bywasik** [comment]
```js
 aboutWindow.loadURL(url.pathToFileURL(path.resolve("src", "about.html")).href);
```

this one work for me
