### ISSUE TITLE
🐛 Bug: Multi-select error invalidates previous selections

### ISSUE THREAD

**Issue by MahmoudHendi1** [KL13NT/clippy#29]
**Describe the bug**
Trying to copy any non-text entity will unselect all the selected entities

**To Reproduce**
1. Copy multiple texts
2. Copy an image
3. Press Shift and select some texts
4. Select an image
5. All entities become unselected

**Expected behavior**
The alert pop up, the image cannot be selected, and other selected entities will remain the same.

**Comment by KL13NT** [comment]
Confirmed on master and dev. Would you like to PR this? I can provide guidance.

**Comment by KL13NT** [comment]
This bug is caused by the App#handleKeyUpClick handler. When the error shows up the `Shift` key is released, thus causing the handler to fire and clear selections. A way to fix this is to add some `error` instance to the state, but this would cause unnecessary, expensive re-renders. 

Adding a `Select multiple` toggle to the buttons list will provide a more accessible interface as well as easier management for the multi-select feature. This would require a complete overhaul of how it's currently implemented. I'll assign myself to this.

**Comment by MahmoudHendi1** [comment]
I thought about the same thing while trying to fix it.
I think calling `e.stopPropagation()` will just fix that.

What I mean, we just don't have to change everything thing, we can just not select the item and then continue the function as usual 🙄

What I did fixed the issue for me.

**Comment by KL13NT** [comment]
~Calling `stopPropagation` stops the bug in regards to `App#handleKeyUpClick` but not for `App#handleKeyUpShift`. The app will still re-render twice at every error, once when the error dialog shows up, setting `state.selecting` to false.~

Just reviewed the code again, `stopPropagation` does work because of the extra condition `!this.state.history.some((e) => e.selected)` at [render.js:90](https://github.com/KL13NT/clippy/blob/master/src/render.js#L90). 

Would you like to give it another shot? If so, I'll re-assign gratefully.

**Comment by MahmoudHendi1** [comment]
Sure I want, but this time I'll listen to some guide. 😶

**Comment by KL13NT** [comment]
All you need to know is in the contribution [pull-request and committing guidelines](https://github.com/KL13NT/clippy/blob/master/CONTRIBUTING.md#pull-requests).
